// ===== pdf-encrypt.js =====
// Minimal pure-JS implementation of the PDF Standard Security Handler
// (Revision 3, RC4-128) to add password protection (encryption) to a PDF
// that has already been generated by pdf-lib (as raw bytes).
//
// This implements the algorithm described in the PDF 1.7 spec (Algorithm 3.2
// for computing the encryption key, Algorithm 3.4 for RC4 string encryption,
// and the standard /Encrypt dictionary). It is widely compatible with Adobe
// Acrobat and most PDF readers for opening password-protected PDFs.
//
// Usage: PDFEncrypt.encrypt(pdfBytes, { userPassword, ownerPassword })
//   -> returns new Uint8Array with /Encrypt dict + encrypted strings/streams

(function (global) {
  const PAD = new Uint8Array([
    0x28, 0xBF, 0x4E, 0x5E, 0x4E, 0x75, 0x8A, 0x41,
    0x64, 0x00, 0x4E, 0x56, 0xFF, 0xFA, 0x01, 0x08,
    0x2E, 0x2E, 0x00, 0xB6, 0xD0, 0x68, 0x3E, 0x80,
    0x2F, 0x0C, 0xA9, 0xFE, 0x64, 0x53, 0x69, 0x7A
  ]);

  // ---- MD5 implementation (pure JS) ----
  function md5(bytes) {
    function rotl(x, c) { return (x << c) | (x >>> (32 - c)); }
    function toBytesLE(arr) {
      const out = [];
      for (const v of arr) {
        out.push(v & 0xff, (v >>> 8) & 0xff, (v >>> 16) & 0xff, (v >>> 24) & 0xff);
      }
      return out;
    }

    const s = [
      7,12,17,22, 7,12,17,22, 7,12,17,22, 7,12,17,22,
      5, 9,14,20, 5, 9,14,20, 5, 9,14,20, 5, 9,14,20,
      4,11,16,23, 4,11,16,23, 4,11,16,23, 4,11,16,23,
      6,10,15,21, 6,10,15,21, 6,10,15,21, 6,10,15,21
    ];
    const K = [];
    for (let i = 0; i < 64; i++) {
      K[i] = Math.floor(Math.abs(Math.sin(i + 1)) * 4294967296) | 0;
    }

    let a0 = 0x67452301, b0 = 0xefcdab89, c0 = 0x98badcfe, d0 = 0x10325476;

    const msgLen = bytes.length;
    const withOne = new Uint8Array(((msgLen + 8) >> 6) * 64 + 64);
    withOne.set(bytes);
    withOne[msgLen] = 0x80;
    const bitLen = msgLen * 8;
    const dv = new DataView(withOne.buffer);
    dv.setUint32(withOne.length - 8, bitLen >>> 0, true);
    dv.setUint32(withOne.length - 4, Math.floor(bitLen / 0x100000000), true);

    for (let offset = 0; offset < withOne.length; offset += 64) {
      const M = [];
      for (let j = 0; j < 16; j++) {
        M[j] = dv.getUint32(offset + j * 4, true);
      }
      let A = a0, B = b0, C = c0, D = d0;
      for (let i = 0; i < 64; i++) {
        let F, g;
        if (i < 16) { F = (B & C) | (~B & D); g = i; }
        else if (i < 32) { F = (D & B) | (~D & C); g = (5 * i + 1) % 16; }
        else if (i < 48) { F = B ^ C ^ D; g = (3 * i + 5) % 16; }
        else { F = C ^ (B | ~D); g = (7 * i) % 16; }
        F = (F + A + K[i] + M[g]) | 0;
        A = D; D = C; C = B;
        B = (B + rotl(F, s[i])) | 0;
      }
      a0 = (a0 + A) | 0; b0 = (b0 + B) | 0; c0 = (c0 + C) | 0; d0 = (d0 + D) | 0;
    }

    return new Uint8Array(toBytesLE([a0, b0, c0, d0]));
  }

  // ---- RC4 ----
  function rc4(key, data) {
    const S = new Uint8Array(256);
    for (let i = 0; i < 256; i++) S[i] = i;
    let j = 0;
    for (let i = 0; i < 256; i++) {
      j = (j + S[i] + key[i % key.length]) & 0xff;
      [S[i], S[j]] = [S[j], S[i]];
    }
    const out = new Uint8Array(data.length);
    let i = 0; j = 0;
    for (let k = 0; k < data.length; k++) {
      i = (i + 1) & 0xff;
      j = (j + S[i]) & 0xff;
      [S[i], S[j]] = [S[j], S[i]];
      out[k] = data[k] ^ S[(S[i] + S[j]) & 0xff];
    }
    return out;
  }

  function padPassword(pwBytes) {
    const out = new Uint8Array(32);
    const len = Math.min(pwBytes.length, 32);
    out.set(pwBytes.subarray(0, len));
    out.set(PAD.subarray(0, 32 - len), len);
    return out;
  }

  function concatBytes(...arrs) {
    let total = 0;
    for (const a of arrs) total += a.length;
    const out = new Uint8Array(total);
    let offset = 0;
    for (const a of arrs) { out.set(a, offset); offset += a.length; }
    return out;
  }

  function int32LE(n) {
    return new Uint8Array([n & 0xff, (n >>> 8) & 0xff, (n >>> 16) & 0xff, (n >>> 24) & 0xff]);
  }

  // Compute owner key (O entry) - Algorithm 3.3
  function computeOwnerKey(ownerPwBytes, userPwBytes, keyLengthBytes) {
    const padded = padPassword(ownerPwBytes.length ? ownerPwBytes : userPwBytes);
    let hash = md5(padded);
    // Revision 3: 50 additional rounds
    for (let i = 0; i < 50; i++) {
      hash = md5(hash.subarray(0, keyLengthBytes));
    }
    const rc4Key = hash.subarray(0, keyLengthBytes);
    let encrypted = padPassword(userPwBytes);
    for (let i = 0; i <= 19; i++) {
      const xorKey = new Uint8Array(keyLengthBytes);
      for (let b = 0; b < keyLengthBytes; b++) xorKey[b] = rc4Key[b] ^ i;
      encrypted = rc4(xorKey, encrypted);
    }
    return encrypted; // 32 bytes
  }

  // Compute encryption key from user password - Algorithm 3.2
  function computeEncryptionKey(userPwBytes, ownerKey, permissions, idBytes, keyLengthBytes) {
    const padded = padPassword(userPwBytes);
    const permBytes = int32LE(permissions >>> 0);
    let input = concatBytes(padded, ownerKey, permBytes, idBytes);
    // Revision 3: add 0xFFFFFFFF if metadata not encrypted - we encrypt metadata, so skip
    let hash = md5(input);
    for (let i = 0; i < 50; i++) {
      hash = md5(hash.subarray(0, keyLengthBytes));
    }
    return hash.subarray(0, keyLengthBytes);
  }

  // Compute U entry (user password validation) - Algorithm 3.5 (Revision 3)
  function computeUserKey(encryptionKey, idBytes) {
    let hash = md5(concatBytes(PAD, idBytes));
    let encrypted = rc4(encryptionKey, hash);
    for (let i = 1; i <= 19; i++) {
      const xorKey = new Uint8Array(encryptionKey.length);
      for (let b = 0; b < encryptionKey.length; b++) xorKey[b] = encryptionKey[b] ^ i;
      encrypted = rc4(xorKey, encrypted);
    }
    // Result is 16 bytes, pad to 32 with arbitrary bytes (spec allows any value)
    const out = new Uint8Array(32);
    out.set(encrypted);
    return out;
  }

  // Object key for RC4 (Algorithm 3.1)
  function objectKey(encryptionKey, objNum, genNum) {
    const extra = new Uint8Array([
      objNum & 0xff, (objNum >> 8) & 0xff, (objNum >> 16) & 0xff,
      genNum & 0xff, (genNum >> 8) & 0xff
    ]);
    const hash = md5(concatBytes(encryptionKey, extra));
    const keyLen = Math.min(encryptionKey.length + 5, 16);
    return hash.subarray(0, keyLen);
  }

  function bytesToHexString(bytes) {
    return Array.from(bytes).map(b => b.toString(16).padStart(2, "0")).join("");
  }

  function bytesToPdfLiteral(bytes) {
    // Use hex string literal <...> to avoid escaping issues
    return "<" + bytesToHexString(bytes) + ">";
  }

  function textEncode(str) {
    return new Uint8Array(Array.from(str).map(c => c.charCodeAt(0) & 0xff));
  }

  // ---- Main: parse PDF, encrypt strings/streams, inject /Encrypt dict ----
  function encrypt(pdfBytes, opts) {
    const userPassword = opts.userPassword || "";
    const ownerPassword = opts.ownerPassword || opts.userPassword || "";
    const keyLengthBytes = 16; // 128-bit RC4

    // Generate a random Document ID (16 bytes)
    const idBytes = new Uint8Array(16);
    if (global.crypto && global.crypto.getRandomValues) {
      global.crypto.getRandomValues(idBytes);
    } else {
      for (let i = 0; i < 16; i++) idBytes[i] = Math.floor(Math.random() * 256);
    }

    const permissions = -44; // allow printing/copying by default (all flags set except reserved)

    const userPwBytes = textEncode(userPassword);
    const ownerPwBytes = textEncode(ownerPassword);

    const ownerKey = computeOwnerKey(ownerPwBytes, userPwBytes, keyLengthBytes);
    const encryptionKey = computeEncryptionKey(userPwBytes, ownerKey, permissions, idBytes, keyLengthBytes);
    const userKey = computeUserKey(encryptionKey, idBytes);

    // Parse the PDF as text/binary mix
    let pdfStr = "";
    for (let i = 0; i < pdfBytes.length; i++) pdfStr += String.fromCharCode(pdfBytes[i]);

    // Find all objects: "N G obj ... endobj"
    const objRegex = /(\d+)\s+(\d+)\s+obj([\s\S]*?)endobj/g;
    let match;
    const objects = [];
    let maxObjNum = 0;

    while ((match = objRegex.exec(pdfStr)) !== null) {
      const objNum = parseInt(match[1], 10);
      const genNum = parseInt(match[2], 10);
      maxObjNum = Math.max(maxObjNum, objNum);
      objects.push({ objNum, genNum, fullMatch: match[0], content: match[3], start: match.index, end: match.index + match[0].length });
    }

    // Build output by processing objects and encrypting strings & stream content
    let result = pdfStr;
    let offsetShift = 0;

    // We rebuild the file from scratch to avoid xref offset issues:
    // simplest robust approach -> use pdf-lib's save() output structure but
    // re-encrypt strings/streams in place, then fix xref by re-saving via pdf-lib again is complex.
    // Instead: encrypt streams and literal strings in place (same byte length where possible),
    // since RC4 keeps byte length identical for streams; for strings we keep hex format
    // with same or padded length is not guaranteed -> so we take a different strategy below.

    return buildEncryptedPdf(pdfBytes, objects, encryptionKey, idBytes, ownerKey, userKey, permissions, keyLengthBytes);
  }

  function bytesToLatin1String(bytes) {
    // Strict 1-byte-to-1-codepoint conversion. We avoid TextDecoder("latin1")
    // here because some JS engines map the C1 control range (0x80-0x9F) to
    // Windows-1252 codepoints instead of passing bytes through raw, which
    // silently corrupts binary PDF data (streams, encrypted strings, etc).
    let out = "";
    const CHUNK = 0x8000;
    for (let i = 0; i < bytes.length; i += CHUNK) {
      out += String.fromCharCode.apply(null, bytes.subarray(i, Math.min(i + CHUNK, bytes.length)));
    }
    return out;
  }

  function buildEncryptedPdf(pdfBytes, objects, encryptionKey, idBytes, ownerKey, userKey, permissions, keyLengthBytes) {
    let pdfStr = bytesToLatin1String(pdfBytes);

    objects.sort((a, b) => a.start - b.start);

    let maxObjNum = 0;
    for (const obj of objects) maxObjNum = Math.max(maxObjNum, obj.objNum);
    const encryptObjNum = maxObjNum + 1;

    // Determine /Root reference from trailer or by locating the Catalog object
    const trailerMatch = pdfStr.match(/trailer\s*<<([\s\S]*?)>>/);
    let rootRef = null;
    if (trailerMatch) {
      const rootMatch = trailerMatch[1].match(/\/Root\s+(\d+)\s+(\d+)\s+R/);
      if (rootMatch) rootRef = `${rootMatch[1]} ${rootMatch[2]} R`;
    }
    if (!rootRef) {
      const catalogMatch = pdfStr.match(/(\d+)\s+0\s+obj[\s\S]*?\/Type\s*\/Catalog/);
      if (catalogMatch) rootRef = `${catalogMatch[1]} 0 R`;
    }

    const newObjects = []; // {objNum, genNum, text}

    for (const obj of objects) {
      const objKey = objectKey(encryptionKey, obj.objNum, obj.genNum);
      let content = obj.content;

      // Encrypt stream data
      content = content.replace(/stream(\r\n|\n)([\s\S]*?)(\r?\n)?endstream/, (m, lineEnd, streamData, trailingNl) => {
        const dataBytes = new Uint8Array(streamData.length);
        for (let i = 0; i < streamData.length; i++) dataBytes[i] = streamData.charCodeAt(i) & 0xff;
        const encrypted = rc4(objKey, dataBytes);
        let encStr = "";
        for (let i = 0; i < encrypted.length; i++) encStr += String.fromCharCode(encrypted[i]);
        return "stream" + lineEnd + encStr + (trailingNl || "") + "endstream";
      });

      // Encrypt literal strings in the dictionary part only (not inside stream)
      const streamIdx = content.indexOf("stream");
      const headPart = streamIdx >= 0 ? content.slice(0, streamIdx) : content;
      const tailPart = streamIdx >= 0 ? content.slice(streamIdx) : "";

      const encryptedHead = headPart.replace(/\(((?:[^()\\]|\\.)*)\)/g, (m, strContent) => {
        const bytes = [];
        for (let i = 0; i < strContent.length; i++) {
          const c = strContent[i];
          if (c === "\\" && i + 1 < strContent.length) {
            const next = strContent[i + 1];
            if (next === "n") { bytes.push(0x0A); i++; }
            else if (next === "r") { bytes.push(0x0D); i++; }
            else if (next === "t") { bytes.push(0x09); i++; }
            else if (next === "b") { bytes.push(0x08); i++; }
            else if (next === "f") { bytes.push(0x0C); i++; }
            else if (next === "(" || next === ")" || next === "\\") { bytes.push(next.charCodeAt(0)); i++; }
            else if (/[0-7]/.test(next)) {
              // octal escape, up to 3 digits
              let oct = next;
              let consumed = 1;
              if (i + 2 < strContent.length && /[0-7]/.test(strContent[i + 2])) { oct += strContent[i + 2]; consumed = 2; }
              if (i + 3 < strContent.length && /[0-7]/.test(strContent[i + 3]) && consumed === 2) { oct += strContent[i + 3]; consumed = 3; }
              bytes.push(parseInt(oct, 8) & 0xff);
              i += consumed;
            }
            else { bytes.push(next.charCodeAt(0)); i++; } // unrecognized escape -> literal char (e.g. \\\n line continuation handled loosely)
          } else {
            bytes.push(c.charCodeAt(0));
          }
        }
        const dataBytes = new Uint8Array(bytes);
        const encrypted = rc4(objKey, dataBytes);
        // Output as a hex string <...> to avoid any literal-string escaping ambiguity
        return bytesToPdfLiteral(encrypted);
      });

      const objText = `${obj.objNum} ${obj.genNum} obj${encryptedHead}${tailPart}endobj`;
      newObjects.push({ objNum: obj.objNum, genNum: obj.genNum, text: objText });
    }

    // Add the /Encrypt object
    const idHex = bytesToPdfLiteral(idBytes);
    const oHex = bytesToPdfLiteral(ownerKey);
    const uHex = bytesToPdfLiteral(userKey);
    const encryptObjText = `${encryptObjNum} 0 obj\n<< /Filter /Standard /V 2 /R 3 /Length 128 /P ${permissions} /O ${oHex} /U ${uHex} >>\nendobj`;
    newObjects.push({ objNum: encryptObjNum, genNum: 0, text: encryptObjText });

    newObjects.sort((a, b) => a.objNum - b.objNum);

    let body = "%PDF-1.7\n";
    const offsets = {};

    let byteLen = body.length;
    for (const o of newObjects) {
      offsets[o.objNum] = byteLen;
      const piece = o.text + "\n";
      byteLen += piece.length;
      body += piece;
    }

    const xrefOffset = byteLen;
    const highestObjNum = newObjects[newObjects.length - 1].objNum;

    let xref = `xref\n0 ${highestObjNum + 1}\n`;
    xref += "0000000000 65535 f \n";
    for (let n = 1; n <= highestObjNum; n++) {
      if (offsets[n] !== undefined) {
        xref += String(offsets[n]).padStart(10, "0") + " 00000 n \n";
      } else {
        xref += "0000000000 00000 f \n";
      }
    }

    const idStr = `[${idHex} ${idHex}]`;
    const trailer = `trailer\n<< /Size ${highestObjNum + 1} /Root ${rootRef} /Encrypt ${encryptObjNum} 0 R /ID ${idStr} >>\nstartxref\n${xrefOffset}\n%%EOF`;

    const finalOut = body + xref + trailer;

    const finalBytes = new Uint8Array(finalOut.length);
    for (let i = 0; i < finalOut.length; i++) finalBytes[i] = finalOut.charCodeAt(i) & 0xff;
    return finalBytes;
  }

  // ---- Decrypt: remove password protection given the correct password ----
  function decrypt(pdfBytes, password) {
    const pdfStr = bytesToLatin1String(pdfBytes);

    // Find the /Encrypt dictionary (could be inline in trailer or as an indirect object)
    const trailerMatch = pdfStr.match(/trailer\s*<<([\s\S]*?)>>/);
    if (!trailerMatch) throw new Error("This PDF doesn't appear to have a readable trailer; it may use a cross-reference stream format that isn't supported.");

    const encryptRefMatch = trailerMatch[1].match(/\/Encrypt\s+(\d+)\s+(\d+)\s+R/);
    if (!encryptRefMatch) throw new Error("This PDF doesn't appear to be password-protected.");

    const encryptObjNum = parseInt(encryptRefMatch[1], 10);

    // Find the /Encrypt object body
    const encObjRegex = new RegExp(`${encryptObjNum}\\s+0\\s+obj([\\s\\S]*?)endobj`);
    const encObjMatch = pdfStr.match(encObjRegex);
    if (!encObjMatch) throw new Error("Could not locate the encryption dictionary in this PDF.");

    const encDictStr = encObjMatch[1];
    const oMatch = encDictStr.match(/\/O\s*<([0-9A-Fa-f]+)>/) || encDictStr.match(/\/O\s*\(([\s\S]*?)\)\s*\/U/);
    const uMatch = encDictStr.match(/\/U\s*<([0-9A-Fa-f]+)>/);
    const pMatch = encDictStr.match(/\/P\s+(-?\d+)/);
    const rMatch = encDictStr.match(/\/R\s+(\d+)/);

    if (!oMatch || !uMatch || !pMatch) throw new Error("Unsupported encryption format in this PDF.");

    function hexToBytes(hex) {
      const out = new Uint8Array(hex.length / 2);
      for (let i = 0; i < out.length; i++) out[i] = parseInt(hex.substr(i * 2, 2), 16);
      return out;
    }

    const ownerKey = hexToBytes(oMatch[1]);
    const permissions = parseInt(pMatch[1], 10);
    const revision = rMatch ? parseInt(rMatch[1], 10) : 3;
    const keyLengthBytes = 16;

    // Find /ID in trailer
    const idMatch = trailerMatch[1].match(/\/ID\s*\[\s*<([0-9A-Fa-f]+)>/);
    if (!idMatch) throw new Error("Could not find the document ID needed for decryption.");
    const idBytes = hexToBytes(idMatch[1]);

    const userPwBytes = textEncode(password || "");
    const encryptionKey = computeEncryptionKey(userPwBytes, ownerKey, permissions, idBytes, keyLengthBytes);

    // Validate password by recomputing the U entry and comparing first 16 bytes
    const computedU = computeUserKey(encryptionKey, idBytes);
    const storedU = hexToBytes(uMatch[1]);
    let matches = true;
    for (let i = 0; i < 16; i++) {
      if (computedU[i] !== storedU[i]) { matches = false; break; }
    }
    if (!matches) {
      throw new Error("Incorrect password. Please check the password and try again.");
    }

    // Find all objects and decrypt their strings/streams (mirror of encrypt, RC4 is symmetric)
    const objRegex = /(\d+)\s+(\d+)\s+obj([\s\S]*?)endobj/g;
    let match;
    const objects = [];
    while ((match = objRegex.exec(pdfStr)) !== null) {
      const objNum = parseInt(match[1], 10);
      const genNum = parseInt(match[2], 10);
      if (objNum === encryptObjNum) continue; // skip the encrypt dict itself
      objects.push({ objNum, genNum, content: match[3] });
    }

    let rootRef = null;
    const rootMatch = trailerMatch[1].match(/\/Root\s+(\d+)\s+(\d+)\s+R/);
    if (rootMatch) rootRef = `${rootMatch[1]} ${rootMatch[2]} R`;

    const newObjects = [];
    for (const obj of objects) {
      const objKey = objectKey(encryptionKey, obj.objNum, obj.genNum);
      let content = obj.content;

      content = content.replace(/stream(\r\n|\n)([\s\S]*?)(\r?\n)?endstream/, (m, lineEnd, streamData, trailingNl) => {
        const dataBytes = new Uint8Array(streamData.length);
        for (let i = 0; i < streamData.length; i++) dataBytes[i] = streamData.charCodeAt(i) & 0xff;
        const decrypted = rc4(objKey, dataBytes); // RC4 is symmetric
        let decStr = "";
        for (let i = 0; i < decrypted.length; i++) decStr += String.fromCharCode(decrypted[i]);
        return "stream" + lineEnd + decStr + (trailingNl || "") + "endstream";
      });

      const streamIdx = content.indexOf("stream");
      const headPart = streamIdx >= 0 ? content.slice(0, streamIdx) : content;
      const tailPart = streamIdx >= 0 ? content.slice(streamIdx) : "";

      const decryptedHead = headPart.replace(/(?<!<)<([0-9A-Fa-f\s]+)>(?!>)|\(((?:[^()\\]|\\.)*)\)/g, (m, hexContent, strContent) => {
        let dataBytes;
        if (hexContent !== undefined) {
          const clean = hexContent.replace(/\s/g, "");
          const padded = clean.length % 2 === 0 ? clean : clean + "0";
          dataBytes = new Uint8Array(padded.length / 2);
          for (let i = 0; i < dataBytes.length; i++) dataBytes[i] = parseInt(padded.substr(i * 2, 2), 16);
        } else {
          const bytes = [];
          for (let i = 0; i < strContent.length; i++) {
            const c = strContent[i];
            if (c === "\\" && i + 1 < strContent.length) {
              const next = strContent[i + 1];
              if (next === "n") { bytes.push(0x0A); i++; }
              else if (next === "r") { bytes.push(0x0D); i++; }
              else if (next === "t") { bytes.push(0x09); i++; }
              else if (next === "b") { bytes.push(0x08); i++; }
              else if (next === "f") { bytes.push(0x0C); i++; }
              else if (next === "(" || next === ")" || next === "\\") { bytes.push(next.charCodeAt(0)); i++; }
              else if (/[0-7]/.test(next)) {
                let oct = next;
                let consumed = 1;
                if (i + 2 < strContent.length && /[0-7]/.test(strContent[i + 2])) { oct += strContent[i + 2]; consumed = 2; }
                if (i + 3 < strContent.length && /[0-7]/.test(strContent[i + 3]) && consumed === 2) { oct += strContent[i + 3]; consumed = 3; }
                bytes.push(parseInt(oct, 8) & 0xff);
                i += consumed;
              }
              else { bytes.push(next.charCodeAt(0)); i++; }
            } else {
              bytes.push(c.charCodeAt(0));
            }
          }
          dataBytes = new Uint8Array(bytes);
        }

        const decrypted = rc4(objKey, dataBytes);
        // Output as hex string to keep parsing unambiguous downstream
        return bytesToPdfLiteral(decrypted);
      });

      const objText = `${obj.objNum} ${obj.genNum} obj${decryptedHead}${tailPart}endobj`;
      newObjects.push({ objNum: obj.objNum, genNum: obj.genNum, text: objText });
    }

    newObjects.sort((a, b) => a.objNum - b.objNum);

    let body = "%PDF-1.7\n";
    const offsets = {};
    let byteLen = body.length;
    for (const o of newObjects) {
      offsets[o.objNum] = byteLen;
      const piece = o.text + "\n";
      byteLen += piece.length;
      body += piece;
    }

    const xrefOffset = byteLen;
    const highestObjNum = newObjects[newObjects.length - 1].objNum;

    let xref = `xref\n0 ${highestObjNum + 1}\n`;
    xref += "0000000000 65535 f \n";
    for (let n = 1; n <= highestObjNum; n++) {
      if (offsets[n] !== undefined) {
        xref += String(offsets[n]).padStart(10, "0") + " 00000 n \n";
      } else {
        xref += "0000000000 00000 f \n";
      }
    }

    const trailer = `trailer\n<< /Size ${highestObjNum + 1} /Root ${rootRef} >>\nstartxref\n${xrefOffset}\n%%EOF`;
    const finalOut = body + xref + trailer;

    const finalBytes = new Uint8Array(finalOut.length);
    for (let i = 0; i < finalOut.length; i++) finalBytes[i] = finalOut.charCodeAt(i) & 0xff;
    return finalBytes;
  }

  global.PDFEncrypt = { encrypt, decrypt };
})(typeof window !== "undefined" ? window : globalThis);
